# Generated by Django 4.0.6 on 2022-07-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_alter_sort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
