# Generated by Django 4.0.6 on 2022-08-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0002_alter_my_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='user_type',
            field=models.CharField(choices=[('Seller Account', 'Seller Account'), ('Buyer Account', 'Buyer Account')], default='Buyer Account', max_length=255),
        ),
    ]
