# Generated by Django 4.0.6 on 2022-08-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Seller', '0002_alter_add_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='image3',
        ),
    ]
