# Generated by Django 4.0.6 on 2022-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Seller', '0003_remove_add_product_image2_remove_add_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
