# Generated by Django 4.0.6 on 2022-08-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='b_image',
            field=models.ImageField(default=1, upload_to='Blogs'),
            preserve_default=False,
        ),
    ]
