# Generated by Django 4.0.6 on 2022-08-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_ip_model_blog_alter_ip_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger_profile',
            name='facebook',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogger_profile',
            name='github',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogger_profile',
            name='instagram',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogger_profile',
            name='twitter',
            field=models.URLField(max_length=255),
        ),
    ]
